"""Convert existing hand-written article HTML into article.md.

Run once to seed the blog directory.  After this, edits happen in the
.md files and the .html is regenerated by tools/build_blog.py.

Idempotent: only writes if the .md does not already exist.
"""
from __future__ import annotations

import re
import sys
from html.parser import HTMLParser
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BLOG_DIR = REPO_ROOT / "pages" / "blog"

# Manually-curated metadata, since some of it (og_url, og_image) is buried
# in <meta> tags and easier to type than to scrape.
META = {
    "2026-07-27/why-this-site-exists": {
        "title": "Why This Site Exists",
        "date_display": "27th July 2026",
        "author": "Takion Kroslin",
        "description": "The origin story of FIVE GUYS ONE DIRECTION — a Mainland China fan project that refuses to let the One Direction archive go dark.",
        "keywords": "One Direction, fan project, China, archive, FIVE GUYS ONE DIRECTION",
        "og_image": "../../../../images/gfx/hero-2015-rect-sml.jpg",
    },
    "2026-07-27/every-july-23rd-we-come-home": {
        "title": "Every July 23rd, We Come Home",
        "date_display": "27th July 2026",
        "author": "Takion Kroslin",
        "description": "A close reading of the song that taught a generation that boybands could grow up, get quiet, and still mean everything.",
        "keywords": "One Direction, Story of My Life, Midnight Memories, essay, FIVE GUYS ONE DIRECTION",
        "og_image": "../../../../images/media/article-images/rect-sml/2aef032aae73e39c7f3547a28fc157e4.jpg",
    },
    "2026-07-27/why-i-love-1d-so-bad": {
        "title": "Why I Love 1D So Bad",
        "date_display": "27th July 2026",
        "author": "Takion Kroslin",
        "description": "How Louis Tomlinson's solo pivot reshaped what a former boybander is allowed to sound like in 2026.",
        "keywords": "One Direction, Louis Tomlinson, solo, essay, FIVE GUYS ONE DIRECTION",
        "og_image": "../../../../images/gfx/filmstrip-louis-smlc4ca.jpg",
    },
    "2026-07-27/ready-to-run": {
        "title": "Ready to Run — The Sound of Choosing Each Other",
        "date_display": "27th July 2026",
        "author": "Takion Kroslin",
        "description": "The Four album track everyone skipped deserves another listen. Here's why.",
        "keywords": "One Direction, Where Do Broken Hearts Go, Four, essay, FIVE GUYS ONE DIRECTION",
        "og_image": "../../../../images/media/article-images/square-sml/dfce33b787ff3ec44499e16b242251be.jpg",
    },
}

# Card-scaler font sizes used on the listing page
SCALERS = {
    "Why This Site Exists": "70%",
    "Every July 23rd, We Come Home": "60%",
    "Why I Love 1D So Bad": "70%",
    "Ready to Run — The Sound of Choosing Each Other": "55%",
}


class _TextExtractor(HTMLParser):
    """Very small HTML->Markdown converter for <p>/<i>/<b>/<a>/<blockquote>.

    Designed only for the body chunks we wrote into blog article .html files —
    it does NOT try to be a full HTML-to-MD converter.  Each <p> becomes a
    blank-line-separated paragraph; inline tags become the obvious Markdown
    equivalents.
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.parts: list[str] = []
        self._skip_depth = 0
        self._buf: list[str] = []

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag in {"script", "style"}:
            self._skip_depth += 1
            return
        if self._skip_depth:
            return
        if tag == "p":
            self._flush_paragraph()
        elif tag == "br":
            self._buf.append("  \n")
        elif tag in {"i", "em"}:
            self._buf.append("*")
        elif tag in {"b", "strong"}:
            self._buf.append("**")
        elif tag == "a":
            href = dict(attrs).get("href", "")
            self._buf.append(f"[")

    def handle_endtag(self, tag: str) -> None:
        if tag in {"script", "style"}:
            self._skip_depth -= 1
            return
        if self._skip_depth:
            return
        if tag == "p":
            self._flush_paragraph()
        elif tag in {"i", "em"}:
            self._buf.append("*")
        elif tag in {"b", "strong"}:
            self._buf.append("**")
        elif tag == "a":
            self._buf.append("]()")  # placeholder — we replace later if href set
            # Note: the converter emits "[label]()" with no URL when href is
            # empty.  The build script (or a human pass) should fix those.
            # We can't easily get the href value into the closing tag with
            # the stdlib HTMLParser, so we re-parse the href from the
            # surrounding tags below.
        elif tag == "blockquote":
            # Promote buffer lines to blockquote prefix
            text = "".join(self._buf).strip()
            self._buf.clear()
            for line in text.splitlines() or [text]:
                self.parts.append("> " + line)
            self.parts.append("")  # blank line

    def handle_data(self, data: str) -> None:
        if self._skip_depth:
            return
        self._buf.append(data)

    def _flush_paragraph(self) -> None:
        text = "".join(self._buf).strip()
        self._buf.clear()
        if text:
            self.parts.append(text)
            self.parts.append("")  # blank line between paragraphs

    def get_markdown(self) -> str:
        # Flush any tail
        self._flush_paragraph()
        # Trim trailing blanks
        while self.parts and self.parts[-1] == "":
            self.parts.pop()
        return "\n".join(self.parts)


def _html_to_markdown(html_chunk: str) -> str:
    """Convert one article body chunk to Markdown."""
    # Drop the trailing <p style="margin-top:2em;"> byrline block — we render
    # bylines from front-matter instead, so we drop it from the body.
    p = _TextExtractor()
    p.feed(html_chunk)
    return p.get_markdown()


def _build_md(rel_dir: str) -> str:
    index_html = BLOG_DIR / rel_dir / "index.html"
    text = index_html.read_text(encoding="utf-8")

    # The body sits between <div class="text"> and the first <footer> tag.
    # Earlier versions of this script tried regexes that ran past the body
    # and pulled in the social links / credits / back-to-top — that produced
    # files where the article.md ended with stray "Twitter", "About", etc.
    # paragraphs.
    start = text.find('<div class="text">')
    end = text.find('<footer>')
    if start == -1 or end == -1:
        raise RuntimeError(f"could not locate text body in {index_html}")
    body_html = text[start + len('<div class="text">'):end]

    meta = META[rel_dir]
    body_md = _html_to_markdown(body_html)
    title = meta["title"]
    scaler = SCALERS.get(title, "70%")

    # Drop the byline paragraph(s) — we render bylines from front matter
    # instead.  Different articles use different byline shapes:
    #   - "<p>— Takion<br>Founder of 5GUYS1DIRECTION</p>"
    #   - "<p>— Takion<br>Founder of 5GUYS1DIRECTION<br>July 23, 2026</p>"
    #   - "<p><i>"The best journeys …"</i></p>" (Ready to Run quote)
    # Walk line by line and drop until we hit a blank line, dropping any
    # continuation lines that look like byline / sign-off / date.
    lines = body_md.splitlines()
    out: list[str] = []
    skipping_byline = False
    for line in lines:
        stripped = line.strip()
        if skipping_byline:
            # Continue dropping until we hit a blank line, then stop
            if stripped == "":
                skipping_byline = False
            continue
        if (
            stripped.startswith("— Takion")
            or stripped.startswith("- Takion")
            or stripped == "Founder of 5GUYS1DIRECTION"
            or stripped == "July 23, 2026"
            or stripped == "27th July 2026"
            or ('"The best journeys' in line and 'forward, together' in line)
        ):
            skipping_byline = True
            continue
        out.append(line)
    body_md = "\n".join(out).rstrip()

    fm_lines = [
        "<!--",
        f"title: {title}",
        f"date: {rel_dir.split('/')[0]}",
        f"slug: {rel_dir.split('/')[1]}",
        f"date_display: {meta['date_display']}",
        f"author: {meta['author']}",
        f"header_img: ../../../../images/gfx/5guys/logo-black.png",
        f"header_img_size: 50% contain",
        f"header_img_position: center",
        f"description: {meta['description']}",
        f"keywords: {meta['keywords']}",
        f"og_image: {meta['og_image']}",
        f"scaler: {scaler}",
        "-->",
        "",
    ]
    return "\n".join(fm_lines) + body_md + "\n"


def main() -> int:
    if not BLOG_DIR.exists():
        print(f"missing blog dir: {BLOG_DIR}", file=sys.stderr)
        return 1
    written = 0
    for rel_dir in META:
        md_path = BLOG_DIR / rel_dir / "article.md"
        if md_path.exists():
            print(f"  exists, skipping: {md_path.relative_to(REPO_ROOT)}")
            continue
        md_text = _build_md(rel_dir)
        md_path.write_text(md_text, encoding="utf-8")
        print(f"  wrote: {md_path.relative_to(REPO_ROOT)}")
        written += 1
    print(f"\nDone. {written} article(s) extracted.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
